import type { AttentionCase, CareRoutine, Senior, TimelineItem } from "./types";

export const seniors: Senior[] = [
  {
    id: "mdm-lim",
    name: "Mdm Lim Siew Lan",
    preferredName: "Mdm Lim",
    initials: "LL",
    language: "English",
    callWindow: "8:00 AM–8:00 PM",
    caregiver: "Joanne Lim",
    caregiverRelationship: "Daughter",
    phoneMasked: "+65 •••• 4821",
    lastContact: "Today, 8:04 AM",
    nextReminder: "Today, 6:30 PM",
    nextReminderLabel: "Dinner check-in",
    attentionCount: 0,
    avatar: "blue",
    status: "active",
  },
  {
    id: "mr-rahman",
    name: "Mr Abdul Rahman",
    preferredName: "Mr Rahman",
    initials: "AR",
    language: "Malay",
    callWindow: "8:30 AM–7:30 PM",
    caregiver: "Nur Aisyah",
    caregiverRelationship: "Care coordinator",
    phoneMasked: "+65 •••• 1093",
    lastContact: "Yesterday, 6:34 PM",
    nextReminder: "Today, 12:30 PM",
    nextReminderLabel: "Lunch check-in",
    attentionCount: 0,
    avatar: "mint",
    status: "active",
  },
  {
    id: "mdm-devi",
    name: "Mdm Kavitha Devi",
    preferredName: "Mdm Devi",
    initials: "KD",
    language: "English",
    callWindow: "9:00 AM–8:00 PM",
    caregiver: "Arun Kumar",
    caregiverRelationship: "Son",
    phoneMasked: "+65 •••• 7354",
    lastContact: "Today, 9:16 AM",
    nextReminder: "Today, 1:00 PM",
    nextReminderLabel: "Afternoon medication",
    attentionCount: 1,
    avatar: "lilac",
    status: "active",
  },
  {
    id: "mr-tan",
    name: "Mr Tan Kok Leong",
    preferredName: "Mr Tan",
    initials: "TK",
    language: "Mandarin",
    callWindow: "8:00 AM–8:30 PM",
    caregiver: "Rachel Tan",
    caregiverRelationship: "Granddaughter",
    phoneMasked: "+65 •••• 6682",
    lastContact: "Today, 8:41 AM",
    nextReminder: "Today, 6:30 PM",
    nextReminderLabel: "Dinner check-in",
    attentionCount: 0,
    avatar: "sand",
    status: "active",
  },
];

export const routines: CareRoutine[] = [
  {
    id: "lim-morning-medication",
    seniorId: "mdm-lim",
    kind: "medication",
    title: "Morning medication",
    caregiverInstruction: "Remind Mdm Lim to take the medication prepared in the morning compartment.",
    schedule: "Daily at 8:00 AM",
    nextRun: "Tomorrow, 8:00 AM",
    status: "active",
    trustPhrase: "Joanne asked me to call about your morning routine.",
  },
  {
    id: "lim-dinner",
    seniorId: "mdm-lim",
    kind: "meal",
    title: "Dinner check-in",
    caregiverInstruction: "Ask whether dinner is available and whether Mdm Lim has eaten.",
    schedule: "Daily at 6:30 PM",
    nextRun: "Today, 6:30 PM",
    status: "active",
    trustPhrase: "Joanne asked me to check in about dinner.",
  },
  {
    id: "rahman-lunch",
    seniorId: "mr-rahman",
    kind: "meal",
    title: "Lunch check-in",
    caregiverInstruction: "Ask whether lunch has arrived and whether Mr Rahman has eaten.",
    schedule: "Weekdays at 12:30 PM",
    nextRun: "Today, 12:30 PM",
    status: "active",
    trustPhrase: "Aisyah from the care team arranged this lunch check-in.",
  },
  {
    id: "devi-afternoon-medication",
    seniorId: "mdm-devi",
    kind: "medication",
    title: "Afternoon medication",
    caregiverInstruction: "Remind Mdm Devi about the medication prepared for the afternoon routine.",
    schedule: "Daily at 1:00 PM",
    nextRun: "Today, 1:00 PM",
    status: "active",
    trustPhrase: "Arun asked me to call about your afternoon routine.",
  },
  {
    id: "tan-dinner",
    seniorId: "mr-tan",
    kind: "meal",
    title: "Dinner check-in",
    caregiverInstruction: "Ask whether dinner is available and whether Mr Tan has eaten.",
    schedule: "Daily at 6:30 PM",
    nextRun: "Today, 6:30 PM",
    status: "active",
    trustPhrase: "Rachel arranged this evening check-in.",
  },
];

export const timeline: TimelineItem[] = [
  {
    id: "timeline-lim-morning",
    seniorId: "mdm-lim",
    routineId: "lim-morning-medication",
    time: "8:00 AM",
    title: "Morning medication",
    kind: "medication",
    status: "self-reported-taken",
    statusLabel: "Self-reported taken",
    detail: "Call completed at 8:04 AM",
  },
  {
    id: "timeline-devi-medication",
    seniorId: "mdm-devi",
    routineId: "devi-afternoon-medication",
    time: "9:15 AM",
    title: "Medication follow-up",
    kind: "medication",
    status: "needs-caregiver",
    statusLabel: "Needs caregiver",
    detail: "Unsure whether medication was already taken",
  },
  {
    id: "timeline-rahman-lunch",
    seniorId: "mr-rahman",
    routineId: "rahman-lunch",
    time: "12:30 PM",
    title: "Lunch check-in",
    kind: "meal",
    status: "due",
    statusLabel: "Due now",
    detail: "Meal delivery expected before the call",
  },
  {
    id: "timeline-devi-afternoon",
    seniorId: "mdm-devi",
    routineId: "devi-afternoon-medication",
    time: "1:00 PM",
    title: "Afternoon medication",
    kind: "medication",
    status: "upcoming",
    statusLabel: "Upcoming",
    detail: "Within permitted call window",
  },
  {
    id: "timeline-lim-dinner",
    seniorId: "mdm-lim",
    routineId: "lim-dinner",
    time: "6:30 PM",
    title: "Dinner check-in",
    kind: "meal",
    status: "upcoming",
    statusLabel: "Upcoming",
    detail: "Ask about food access before meal status",
  },
  {
    id: "timeline-tan-dinner",
    seniorId: "mr-tan",
    routineId: "tan-dinner",
    time: "6:30 PM",
    title: "Dinner check-in",
    kind: "meal",
    status: "upcoming",
    statusLabel: "Upcoming",
    detail: "Preferred language: Mandarin",
  },
];

export const attentionCases: AttentionCase[] = [
  {
    id: "attention-devi-unsure",
    seniorId: "mdm-devi",
    routineId: "devi-afternoon-medication",
    priority: "contact-now",
    priorityLabel: "Contact now",
    title: "Unsure whether medication was already taken",
    createdAt: "Today, 9:16 AM",
    context: "CareCall gave no dosage or repeat-dose instruction. Mdm Devi requested a call from Arun.",
    nextAction: "Call Mdm Devi or primary caregiver Arun Kumar before the 1:00 PM routine.",
  },
  {
    id: "attention-rahman-delivery",
    seniorId: "mr-rahman",
    routineId: "rahman-lunch",
    priority: "today",
    priorityLabel: "Follow up today",
    title: "Confirm meal delivery arrangement",
    createdAt: "Yesterday, 6:37 PM",
    context: "Mr Rahman reported that yesterday's dinner delivery arrived later than expected.",
    nextAction: "Confirm today's delivery window with the care coordinator.",
  },
];
