import { useRef, useState } from "react";
import type { CareRoutine, Senior } from "../carecall/types";
import type { CareCallRequest } from "../workflows/carecall";
import { Icon } from "./Icon";
import { useModalDialog } from "./useModalDialog";

export function ScheduleActivationSheet({ routine, senior, onClose, onActivated }: { routine: CareRoutine; senior: Senior; onClose: () => void; onActivated: (token: string) => void }) {
  const [phone, setPhone] = useState(""); const [operatorId, setOperatorId] = useState("mei-chen"); const [code, setCode] = useState("");
  const [frequency, setFrequency] = useState<"daily" | "weekdays">("daily"); const [time, setTime] = useState("08:00");
  const [reviewDate, setReviewDate] = useState(""); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const titleRef = useRef<HTMLHeadingElement>(null); const sheetRef = useRef<HTMLElement>(null);
  useModalDialog(sheetRef, titleRef, onClose);
  async function activate() {
    setBusy(true); setError("");
    try {
      const login = await fetch("/api/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ operator_id: operatorId, access_code: code }) });
      const loginBody = await login.json() as { token?: string; message?: string }; if (!login.ok || !loginBody.token) throw new Error(loginBody.message ?? "Operator sign-in failed.");
      const call: CareCallRequest = { workflow: "carecall", request_key: crypto.randomUUID(), organisation: { name: "Queenstown Care Team", timezone: "Asia/Singapore" }, senior: { id: senior.id, preferred_name: senior.preferredName, phone_e164: phone, language: "English", authority_confirmed: true, permitted_call_window: senior.callWindow }, routine: { id: routine.id, kind: routine.kind, title: routine.title, caregiver_instruction: routine.caregiverInstruction, caregiver_name: senior.caregiver, trust_phrase: routine.trustPhrase }, authorization: { exactly_one_call: true, authorized_at: new Date().toISOString() } };
      const response = await fetch("/api/carecall/schedules", { method: "POST", headers: { authorization: `Bearer ${loginBody.token}`, "content-type": "application/json" }, body: JSON.stringify({ call, frequency, time_sgt: time, review_date: new Date(`${reviewDate}T23:59:59+08:00`).toISOString(), skip_dates: [], recurring_authority_confirmed: true }) });
      const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Schedule activation failed.");
      onActivated(loginBody.token); onClose();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Schedule activation failed."); setBusy(false); }
  }
  return <div className="sheet-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section aria-labelledby="schedule-title" aria-modal="true" className="call-sheet execution-sheet" ref={sheetRef} role="dialog"><header className="call-sheet__header"><div><span className="dry-run-badge"><Icon name="calendar" size={14} /> Recurring authorization</span><h2 id="schedule-title" ref={titleRef} tabIndex={-1}>Activate {routine.title.toLowerCase()}</h2><p>{senior.preferredName} · every call remains visible and stoppable</p></div><button aria-label="Close schedule authorization" className="icon-button" onClick={onClose} type="button"><Icon name="close" /></button></header><div className="call-sheet__content execution-content"><label className="execution-field"><span>Authorized senior phone number</span><input autoComplete="off" inputMode="tel" onChange={(e) => setPhone(e.target.value.trim())} placeholder="+65…" type="tel" value={phone} /></label><label className="execution-field"><span>Operator ID</span><input autoComplete="username" onChange={(e) => setOperatorId(e.target.value)} value={operatorId} /></label><label className="execution-field"><span>Operator sign-in code</span><input autoComplete="current-password" onChange={(e) => setCode(e.target.value)} type="password" value={code} /></label><div className="schedule-fields"><label className="execution-field"><span>Frequency</span><select onChange={(e) => setFrequency(e.target.value as "daily" | "weekdays")} value={frequency}><option value="daily">Daily</option><option value="weekdays">Weekdays</option></select></label><label className="execution-field"><span>Singapore time</span><input onChange={(e) => setTime(e.target.value)} type="time" value={time} /></label><label className="execution-field"><span>Review date</span><input onChange={(e) => setReviewDate(e.target.value)} type="date" value={reviewDate} /></label></div><label className="authorization-check"><input checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} type="checkbox" /><span>I confirm this senior is enrolled for this visible schedule, understand when calls occur, and know how to pause or cancel it.</span></label>{error && <div className="execution-error" role="alert">{error}</div>}</div><footer className="call-sheet__footer"><div><Icon name="info" size={17} /><span>Signed queue delivery creates one CALL-E request per authorized occurrence.</span></div><button className="primary-button" disabled={!confirmed || !phone || !operatorId || !code || !reviewDate || busy} onClick={activate} type="button">{busy ? "Activating…" : "Activate schedule"}</button></footer></section></div>;
}
